table dim_airline
	lineageTag: fa56f350-d0be-4ade-891f-eba252368847

	column airline_key
		dataType: int64
		formatString: 0
		lineageTag: a147a63f-052b-4256-9c7e-c610adf45539
		summarizeBy: none
		sourceColumn: airline_key

		annotation SummarizationSetBy = Automatic

	column carrier_code
		dataType: string
		lineageTag: d98ed242-a17a-4162-ab01-ecb025434e4e
		summarizeBy: none
		sourceColumn: carrier_code

		annotation SummarizationSetBy = Automatic

	column carrier_name
		dataType: string
		lineageTag: bd430ea2-433f-4713-9ac5-4cbc356ff59e
		summarizeBy: none
		sourceColumn: carrier_name

		annotation SummarizationSetBy = Automatic

	partition dim_airline = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\nzara\OneDrive\DBS\Data Visualisation\Assignment CA2\csv_final\dim_airline.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"airline_key", Int64.Type}, {"carrier_code", type text}, {"carrier_name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

